### ISSUE TITLE
Build instructions are inaccurate

### ISSUE THREAD

**Issue by jduck** [0vercl0k/rp#10]
1. These instructions don't seem to work:

```
# unix => cd build/ && cmake .. && make
```

First of all, "build" doesn't exist because git cannot store empty directories. Second, running "cmake .." puts the makefiles in .. too. So something more accurate would be:

```
# mkdir build && cd $_ && cmake .. && cd .. && make
```

**Comment by jduck** [comment]
Apparently my checkout was out of date :-/

The only thing still valid about this issue is the "cd build" part...

**Comment by 0vercl0k** [comment]
The only build instructions I wrote are here https://github.com/0vercl0k/rp/tree/next & are accurate.

Cheers,
0vercl0k

**Comment by jduck** [comment]
Agreed. Sending a PR to correct what I'm talking about.
