### ISSUE TITLE
vdso

### ISSUE THREAD

**Issue by mistressofjellyfish** [0vercl0k/rp#15]
Hey,

rp++ is awesome, but I think it should be able to search the vdso for gadgets.

**Comment by 0vercl0k** [comment]
One easy way to deal with this could be to raw dump the section of memory &
load it via --raw; not ideal but can be of help if you need that fast!

Cheers,
0vercl0k

2015-12-22 15:53 GMT-08:00 Matthias Bogad <notifications@github.com>:
