### ISSUE TITLE
ROP gadget not ending in RET instruction

### ISSUE THREAD

**Issue by HolmesSherlock** [0vercl0k/rp#20]
It seems `rp++` is pulling out a few ROP gadgets which do not end in `RET` instruction. Precisely, is such a gadget as below a valid one and by design?

`0x08048740: adc edi, dword [ebx+0x080498D8] ; nop  ; sub ebx, 0x04 ; call eax ;  (1 found)`

**Comment by 0vercl0k** [comment]
The definition of a ROP-gadget in the tool is "a sequence of instructions
ending with a branching instruction" - so yes this is expected! Here is the
"valid" branching instructions if you are curious:
https://github.com/0vercl0k/rp/blob/master/src/bearopgadgetfinder.cpp#L146.

Cheers

2016-12-24 21:50 GMT-08:00 Dipanjan Das <notifications@github.com>:
