### ISSUE TITLE
Feature Request - Raw Bytes w/ results

### ISSUE THREAD

**Issue by jstaursky** [0vercl0k/rp#26]
Could you create an option that would show the raw byte values corresponding with the gadget instructions found? Would lessen some tedium of doing it manually.

**Comment by 0vercl0k** [comment]
I'm kinda curious - what's your use case exactly?

Cheers

Le dim. 21 févr. 2021 à 12:36, jstaursky <notifications@github.com> a
écrit :

**Comment by jstaursky** [comment]
Its helpful for finding unintended subinstructions
for example, say I find 
```nasm
add dword [eax], 0xdeafcafe
```
If I see its corresponding byte pattern `raw bytes = 0x81, 0x00, 0xfe, 0xca, 0xaf, 0xde`
I can recognize that
```nasm
retf 0xdeaf
```
is a subsequence, as it has bytes `raw bytes = 0xca, 0xaf, 0xde`
I'm not a savant and know the full x86 architecture or anything, but recognizing a few patterns is still useful.

**Comment by 0vercl0k** [comment]
But in that case the `ret 0xdeaf` should also be in the output list of
gadgets; and it should be close as well (I think the gadgets are displayed
ordered by address) so I am not sure if it's really useful 🤔

Cheers

Le mar. 23 févr. 2021 à 08:30, jstaursky <notifications@github.com> a
écrit :

**Comment by jstaursky** [comment]
Ah well I suppose its just up to my personal preference then. I found other tools to accomplish this anyway. So we both win. I'll close the issue.

**Comment by 0vercl0k** [comment]
Happy to write a patch for you that does it, it should be pretty easy - but
not sure how useful it is for everybody; that's why I asked the question :)

Cheers

Le mer. 24 févr. 2021 à 12:11, jstaursky <notifications@github.com> a
écrit :
