### ISSUE TITLE
Feature Request - Show output without coloring

### ISSUE THREAD

**Issue by jstaursky** [0vercl0k/rp#27]
this makes it difficult to use the results inside of a pipe.

For example

Currently I need to add `sed 's/\x1b\[[0-9;]*m//g'` before I can use it
```
./rp++ -f <program> -r 3 --unique | cut -d: -f1 | perl -ne 'print if $_ =~ /0x/'\
 | sed 's/\x1b\[[0-9;]*m//g' |xargs -I% r2 -a x86 -b 32 -q -c 's %;pd 2' <program>
```

**Comment by 0vercl0k** [comment]
Have you tried the `modern` branch? I seem to remember that there's some
support for that cf `should_emit_color` & `COLORS_ENABLED`.

Let me know.

Cheers

Le dim. 21 févr. 2021 à 13:01, jstaursky <notifications@github.com> a
écrit :

**Comment by jstaursky** [comment]
Ah my bad, forgot I downloaded the last release. Sorry been a sleep deprived week.

**Comment by 0vercl0k** [comment]
No worries :)

Cheers

Le mar. 23 févr. 2021 à 08:22, jstaursky <notifications@github.com> a
écrit :
