### ISSUE TITLE
make next branch the new master

### ISSUE THREAD

**Issue by jtpereyda** [0vercl0k/rp#28]
The v2-beta release seems to work great. Can we merge next into master (therefore making v2-beta the new recommended release in the README)?

**Comment by 0vercl0k** [comment]
I am planning to put the codebase back in order for the 1k star anniversary - hopefully I'll get to do it before the end of the year. The plan will be to retire the v1 once this is done yes :).

Cheers

**Comment by jtpereyda** [comment]
Can't wait! FWIW, the v2-beta is so nice it could probably be "released" now. IMO. :)

I especially appreciate the feature that prints out the instruction bytes along with the mnemonic -- this makes it way more usable for me right now.

**Comment by 0vercl0k** [comment]
Done in #30.

Cheers
